[workspace]
members = [
  "txkit-builtin",
  "txkit-c-api",
  "txkit-cli",
  "txkit-core",
  "txkit-impl",
]

[patch.crates-io]
txkit-core = { path = "txkit-core" }
txkit-impl = { path = "txkit-impl" }
txkit-builtin = { path = "txkit-builtin" }
