language = "C"
cpp_compat = true

include_guard = "_TXKIT_H_"
includes = ["txkit_extra.h"]

tab_width = 4
documentation_style = "doxy"

[defines]
"feature = cpu" = "TXKIT_HAS_CPU"
"feature = gpu" = "TXKIT_HAS_GPU"

[export]
include = [
	"DebugParams",
	"GradientNoiseParams",
	"SimplexNoiseParams",
	"ValueNoiseParams",
	"WhiteNoiseParams",
]

prefix = "TxKit_"

[export.rename]
MethodBox = "Method"
RegistryBox = "Registry"
MappedImageDataReadBox = "MappedImageDataRead"
MappedImageDataWriteBox = "MappedImageDataWrite"

[fn]
prefix = "TXKIT_API"
sort_by = "Name"

[struct]
derive_constructor = true

[enum]
prefix_with_name = true

[parse]
parse_deps = true
include = ["cgmath", "tinygl"]

[parse.expand]
crates = ["txkit-core", "txkit-builtin"]
