language = "C"
cpp_compat = true

include_guard = "TXKIT_H"

tab_width = 4

documentation_style = "doxy"

[defines]
"feature = cpu" = "TXKIT_HAS_CPU"
"feature = gpu" = "TXKIT_HAS_GPU"

[export]
include = [
	"WhitenoiseParams",
	"DebugParams",
]

[export.rename]
MethodBox = "Method"
MappedImageDataReadBox = "MappedImageDataRead"
MappedImageDataWriteBox = "MappedImageDataWrite"

[fn]
sort_by = "Name"

[struct]
derive_constructor = true

[enum]
prefix_with_name = true

[parse]
parse_deps = false

[parse.expand]
crates = ["txkit"]
all_features = true
