[package]
name = "txkit-c-api"
version = "0.1.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
edition = "2018"

[lib]
name = "ctxkit"
crate_type = ["cdylib"]

[dependencies]
txkit-core = "=0.1.0"
txkit-builtin = "=0.1.0"

env_logger = "0.8"
lazy_static = "1.4.0"
libc = "0.2"
