name: Build

on: push

jobs:
  build:
    name: Check txkit
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install Windows dependencies
        run: choco install ninja
        if: matrix.os == 'windows-latest'
      - run: cargo check

# vim: ft=yaml:ts=2:sw=2:et
