name: Build

on: push

jobs:
  build:
    name: Build txkit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo check

# vim: ft=yaml:ts=2:sw=2:et
